[package]
name = "selfie"
version = "0.1.0"
edition = "2021"

[dependencies]
console = "0.15.10"
serde = { version = "1.0.218", features = ["derive"] }
serde_yaml = "0.9.34"
shellexpand = "3.1.0"
thiserror = "2.0.11"

[dev-dependencies]
dirs = "5.0.1"
